Signup screen
enzhdanova/task2_words_factory pull request #2
Opened 2022-03-15 17:04 UTC by enzhdanova

Пока ждала ревью, на выходных почти сделала экран авторизации.
Доделала уже с учетом замечаний первого ревью.

2022-03-27 13:56 UTC, ShkiTTer requested changes

2022-03-27 13:56 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/AppRegexp.kt
> +class AppRegexp {
Думаю лучше сделать это объектом и назвать как-то типа `RegexpUtils`

2022-03-27 13:56 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/data/AuthRepositoryImpl.kt
> +    private val errorMessage = "Возникла проблема при получении данных"
Эти сообщения следует хранить в ресурсах, а не в константах, тем более репозитория.

2022-03-27 13:56 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/data/AuthRepositoryImpl.kt
> +            Result.success(User(name = user.name, email = user.email, password = ""))
Если поле пароль тут пустое, то может оно и не нужно в этой модельке?

2022-03-27 13:56 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/data/UserDataSource.kt
> +    @IoDispatcher private val ioDispatcher: CoroutineDispatcher
Можно просто в withContenxt передавать `Dispatchers.IO`. Тут на мой взгляд он лишний

2022-03-27 13:56 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/SignUpScreenActivity.kt
> +        viewModel.getUser()
Кажется, что этот метод можно просто вызывать в блоке `init` у ViewModel

2022-03-27 14:12 UTC, enzhdanova commented on app/src/main/java/com/example/task/wordsfactory/data/AuthRepositoryImpl.kt
> +    private val errorMessage = "Возникла проблема при получении данных"
Т.е. прокинуть сам факт ошибки до активити/фрагмента и там вывести сообщение используя ресурсы?

2022-03-27 15:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/data/AuthRepositoryImpl.kt
> +    private val errorMessage = "Возникла проблема при получении данных"
Да, именно так

2022-04-01 09:06 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/data/AuthRepositoryImpl.kt
> +            Result.success(User(name = user.name, email = user.email, password = ""))
Так все-таки, что с этим полем?

2022-04-01 09:06 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/viewmodel/SignUpViewModel.kt
> +            if (result.isSuccess) {
У `Result` есть классные метод для того, чтобы избегать этого условия - `onSuccess`, `onFailure`

2022-04-02 06:14 UTC, enzhdanova commented on app/src/main/java/com/example/task/wordsfactory/data/AuthRepositoryImpl.kt
> +            Result.success(User(name = user.name, email = user.email, password = ""))
Очень странно, помню, что исправляла этот момент.
Поле в модельке убрала совсем.

2022-04-03 06:52 UTC, ShkiTTer approved these changes

2022-04-10 15:43 UTC, merged