Dictionary screen
enzhdanova/task2_words_factory pull request #3
Opened 2022-04-04 09:33 UTC by enzhdanova

2022-04-23 12:52 UTC, ShkiTTer requested changes

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/di/DictionaryModule.kt
> +        const val baseUrl = "https://api.dictionaryapi.dev/"
Базовый URL к апишке лучше задавать через Gradle скрипт с помощью переменных BuildConfig и получать его потом оттуда. Это поможет использовать в будущем несколько вариантов сборки приложения. Задаются с помощью `buildConfigField` - https://developer.android.com/studio/build/gradle-tips#simplify-app-development

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/utils/MeaningWordItemDecoration.kt
> +        val margin4 = parent.context.resources.getDimensionPixelSize(R.dimen.margin_4)
Эти отступы ты получаешь из ресурсов всякий раз, как вызывается этот метод - а он вызывается на каждое изменение скрола ресайклера, т.е. очень часто. Лучше сделать получение вне метода, а в методе уже просто использовать

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/utils/WordMeaningAdapter.kt
> +            textviewExample.text  = HtmlCompat.fromHtml("<font color='$color'>$example_str</font> ${data.example}", HtmlCompat.FROM_HTML_MODE_LEGACY)
Для выделения куска строки цветом (или других изменений с ней) стоит использовать `SpannableStings`, а не HTML. Это работает сильно быстрее.
https://medium.com/androiddevelopers/spantastic-text-styling-with-spans-17b0c16b4568

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/DictionaryFragment.kt
> +        const val TAG = "DictionaryFragment"
Для тега лучше использовать следующую запись - `val TAG: String = DictionaryFragment::class.java.simpleName`

Результат будет тот же, но если ты вдруг поменяешь название фрагмента, то не придется менять и тег - он поменяется сам

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/DictionaryFragment.kt
> +        fun getFragment(): Fragment {
Этот метод лучше назвать `newInstance` т.к. ты каждый раз создаешь новый экземпляр фрагмента, а не возвращаешь все время один и тот же

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/DictionaryFragment.kt
> +    var mediaPlayer: MediaPlayer? = null
Плеер должен быть приватным

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/DictionaryFragment.kt
> +    private fun init() {
Лучше назвать метод `initView` - так ты добавишь в него конкретики, а то сейчас вообще не понятно, что он конкретно инициализирует

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/ErrorDialogFragment.kt
> +        const val ERROR_TAG = "error_tag"
С тегом аналогично обычному фрагменту

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/ErrorDialogFragment.kt
> +        fun getErrorDialog(errorMessage: String): ErrorDialogFragment {
Метод лучше назвать `create` или `createDialog`, потому что всегда создается новый экземпляр

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/ErrorDialogFragment.kt
> +        return activity?.let {
Диалог не всегда показывается из активити - его можно показывать из другого диалога или фрагмента. Поэтому для контекста тут лучше использовать метод `requireContext`

2022-04-23 12:52 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/viewmodel/DictionaryViewModel.kt
> +            result.fold(
Методы `onSuccess` и `onFailure` можно вызывать без обертки в `fold`

2022-04-24 10:28 UTC, enzhdanova commented on app/src/main/java/com/example/task/wordsfactory/ui/viewmodel/DictionaryViewModel.kt
> +            result.fold(
Переделала, используя метод `getOrNull` вместо `fold`

2022-04-27 13:28 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/viewmodel/DictionaryViewModel.kt
> +            result.fold(
Можно и так конечно, но я имел в виду несколько другое)

2022-04-27 13:28 UTC, ShkiTTer commented
Также не забудь поправить конфликты перед тем, как сливать

2022-04-27 13:28 UTC, ShkiTTer approved these changes

2022-04-27 13:40 UTC, enzhdanova commented on app/src/main/java/com/example/task/wordsfactory/ui/viewmodel/DictionaryViewModel.kt
> +            result.fold(
Тогда, объясни пожалуйста, как надо/можно, я не поняла, если честно=)

2022-04-29 03:15 UTC, merged