Training screen
enzhdanova/task2_words_factory pull request #6
Opened 2022-06-07 12:58 UTC by enzhdanova

2022-06-09 04:05 UTC, ShkiTTer requested changes

2022-06-09 04:05 UTC, ShkiTTer commented on app/build.gradle
> +    kapt "com.google.dagger:hilt-compiler:2.38.1"
А чего версию хилта понизила?

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/data/datasource/LocalDataSource.kt
> +            val newCoefficient = dictionaryDao.studyCoefficient(word.word) - 1
Тут оступы слегка поехали. Чтобы такое не упускать, то можно почаще использовать Ctrl + Alt + L, которые все причешет. А если его еще и немного настроить, то и лишние импорты будет подчищать

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/data/datasource/LocalDataSource.kt
> +    suspend fun increaseCoefficient(word: Word): Result<Boolean>  {
Я бы тут оставил только один метод вместо increase и decrease. Потому что все отличие в них это в одной строчке плюс на минус меняется. Можно просто коэффициент считать раньше, а сюда уже передавать посчитанный

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/data/datasource/LocalDataSource.kt
> +    private fun wordToWordDB(word: Word, studyCoefficient: Long) = WordBD(
Подобные методы преобразования можно выносить в сами модельки. Например, тут можно вынести в WordDb в companion object метод, который будет преобразовывать Word в WordDb

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +                binding?.buttonStart?.visibility = View.VISIBLE
Тут можно избежать лишнего дублирования кода и записать так:

`val (isVisible, textRes) = if (count == 0L) false to R.string.first_resource else true to R.string.second_resource`

А после уже вьюхам передавать нужное значение

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +        binding?.progressTimer?.visibility = View.GONE
Тут лучше использовать свойство `isVisible`

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +        binding?.progressTimer?.visibility = View.VISIBLE
Тут аналогично пункту выше

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +            duration = 5000
Стоит вынести в константу. Хотя бы потому что ты уже дважды это значение используешь. Да и просто будет понятнее, что это за числа

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +        val animatorProgress = ValueAnimator.ofInt(100, 0).apply {
Эти значения тоже лучше в константы вынести

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +            duration = 1000
Туда же в константы

2022-06-09 04:05 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +            Toast.makeText(context, "Тут будет переход дальше!", Toast.LENGTH_LONG).show()
Строчку в ресурсы надо вынести

2022-06-09 06:55 UTC, enzhdanova commented on app/build.gradle
> +    kapt "com.google.dagger:hilt-compiler:2.38.1"
Потому что когда с 2.38.1 поменяла на 2.40.1 у меня стал падать с ошибкой:

> error: package dagger.hilt.android.flags does not exist
Хотя сейчас проверила и все нормально, возможно где-то с версиями недоглядела.

2022-06-09 06:56 UTC, enzhdanova commented on app/src/main/java/com/example/task/wordsfactory/data/datasource/LocalDataSource.kt
> +            val newCoefficient = dictionaryDao.studyCoefficient(word.word) - 1
Вообще регулярно этим пользуюсь и перед реквестом все проверяю, тут, наверное, пропустила случайно.

2022-06-09 07:27 UTC, enzhdanova commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +                binding?.buttonStart?.visibility = View.VISIBLE
Тут просто большое спасибо =)

2022-06-20 09:17 UTC, ShkiTTer requested changes

2022-06-20 09:17 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/database/entity/MeaningBD.kt
> +        fun meaningToMeaningDB(meaning: Meaning, wordId: Long) = MeaningBD(
Как-то слишком много `meaning` в одном месте. Как правило, модели, которые используются в приложении называются доменными моделями (domain model). Это именно модели, которыми оперирует само приложения, а для БД и сетового слоя свои. Поэтому такие методы можно называть `fromDomain` и `toDomain`, когда речь идет про простую конвертацию доменной модели в ее представление для БД, например

2022-06-20 09:17 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/database/entity/WordBD.kt
> +        fun toWordDB(word: Word) = WordBD(
Тут аналогично комментарию выше

2022-06-20 09:17 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +            val (isVisible, textString) = if (it.countWord == 0L) false to getString(R.string.add_word_in_dictionary)
Когда у тебя получается слишком длинное условие, то стоит использовать фигурные скобки для блоков после if и else даже если там одна строка. Читать становится кратно проще

2022-06-20 09:17 UTC, ShkiTTer commented on app/src/main/java/com/example/task/wordsfactory/ui/view/TrainingFragment.kt
> +        private const val timerDuration = 5000L
Константы принято именовать в верхнем регистре и snake_case, т.е. `TIMER_DURATION`

2022-06-21 09:41 UTC, ShkiTTer approved these changes

2022-06-21 09:41 UTC, ShkiTTer commented
Перед тем как будешь сливать, поправь конфликты только

2022-06-21 16:40 UTC, merged